export const PERMISSIONS = {
  SETTINGS_READ: "settings.read",
  SETTINGS_WRITE: "settings.write",
  BACKUP_EXPORT: "backup.export",
  BACKUP_RESTORE: "backup.restore",
  ACTIVITY_READ: "activity.read",
  DASHBOARD_READ: "dashboard.read",
  INVENTORY_READ: "inventory.read",
  INVENTORY_WRITE: "inventory.write",
  INVENTORY_PURCHASE: "inventory.purchase",
  INVENTORY_ADJUST: "inventory.adjust",
  INVENTORY_REPORT: "inventory.report",
  PRODUCTION_READ: "production.read",
  PRODUCTION_WRITE: "production.write",
  PRODUCTION_EXECUTE: "production.execute",
  PRODUCTION_ADJUST_COST: "production.adjust.cost",
  PRODUCTION_REPORT: "production.report",
  HR_READ: "hr.read",
  HR_WRITE: "hr.write",
  PAYROLL_READ: "payroll.read",
  PAYROLL_EXECUTE: "payroll.execute",
  PAYROLL_ADJUST: "payroll.adjust",
  PAYROLL_REPORT: "payroll.report",
  SALES_READ: "sales.read",
  SALES_WRITE: "sales.write",
  SALES_VALIDATE: "sales.validate",
  SALES_CANCEL: "sales.cancel",
  SALES_PAYMENT: "sales.payment",
  SALES_REPORT: "sales.report",
  REPORTS_READ: "reports.read",
  REPORTS_EXPORT: "reports.export",
  REPORTS_FINANCIAL: "reports.financial",
  ANALYTICS_READ: "analytics.read",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
